version: '2'
volumes:
  resin-data: {}
services:
  signage:
    restart: always
    build: ./vue
    volumes: 
      - 'resin-data:/usr/src/app/files'
    privileged: true
    labels:	
      io.balena.features.dbus: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.balena-socket: '1'
